### ISSUE TITLE
ValuesJsonConverter doesn't pass JsonSerializer through to ToObject

### ISSUE THREAD

**Issue by Turnerj** [RehanSaeed/Schema.NET#104]
The `ToObject` calls on `JObject` or `JToken` etc inside the `ValuesJsonConverter` don't pass the current serializer. This is a problem as custom converters on the serializer are never passed through (eg. `StringEnumConverter`) to the inner deserialization of the token/object.

This would affect all nested properties that have `IThing` (or anything derived from it) as a potential value.

The fix is basically just passing the instance of `JsonSerializer` through to the `ToObject` method calls within `ValuesJsonConverter`.

I would add a specific way to reproduce this however I came into this issue from a different/complicated angle. I was trying to deserialize a `BreadcrumbList` where the list item's "item" field wouldn't deserialize because it was an `IThing` and there was no defined type. When I tried to use my own converter (basically taking the `IThing` the serialization process saw and making it instantiate `Thing`), I saw my converter was never passed down the line into the nested properties.

I'm not sure if it is worth fixing for JSON.Net or just something to keep in mind for #100 .

**Comment by RehanSaeed** [comment]
I'm wondering if we can switch to https://github.com/RehanSaeed/Schema.NET/pull/100 which is fixed but still work in progress. Lets see.
