### ISSUE TITLE
OneOrMany handling of Value types vs Reference types with default values

### ISSUE THREAD

**Issue by Turnerj** [RehanSaeed/Schema.NET#116]
I've been looking at further performance and allocation optimisations - one that I have been messing with is making `OneOrMany` only internally hold an array rather than an array and a single item.

While for the most part this is just an implementation change (no API changes), it did show a few things, that are strange to me, with how `OneOrMany` works.

[`OneOrMany` won't store a single null value (Count == 0)](https://github.com/RehanSaeed/Schema.NET/blob/master/Source/Schema.NET/OneOrMany%7BT%7D.cs#L96) but will allow multiple null values (Count > 1). This is strange behaviour though is backed up in the tests like in the `CarTest`. 

https://github.com/RehanSaeed/Schema.NET/blob/master/Tests/Schema.NET.Test/core/CarTest.cs#L20

I feel that it should be consistent - if any null values (or empty strings) are provided, they are ignored/not added internally to the `OneOrMany`. This is what the implicit conversion logic does but I think the constructor should be handling that instead. I would likely inline the implicit conversion logic to the constructor(s) instead.

The other thing I found is if `OneOrMany` is a value type, it always has a value. I understand this from the perspective that `int` etc can't be null but at the same time, it doesn't make sense to me why a default `OneOrMany<int>` actually has anything at all. I'm not sure if it is like this due to the previous implementation (by holding a single `item` value of `T` which would not be null for value types) or if it was intentional.

This is what I've currently built (builds upon changes in #109): https://gist.github.com/Turnerj/6d0400887912f454ef2be033c682ff4e#file-oneormany-cs

Really this issue is just to gauge your thoughts on such a change? Various tests would need updating as a number play on the logic that something like `OneOrMany<int>` should always have a value. (I can work to keep that logic but I figure while I'm doing this update, I might find out if it is even necessary)

I'm happy to do the changes - probably in #109 or otherwise after that has merged. Right now it looks like a 3% allocation improvement (in the Book benchmark) though I think there is probably more I can get out of it.

**Comment by RehanSaeed** [comment]
> I feel that it should be consistent - if any null values (or empty strings) are provided, they are ignored/not added internally to the OneOrMany. This is what the implicit conversion logic does but I think the constructor should be handling that instead. I would likely inline the implicit conversion logic to the constructor(s) instead.

This sounds like a bug. The above sounds sensible.

> The other thing I found is if OneOrMany is a value type, it always has a value. I understand this from the perspective that int etc can't be null but at the same time, it doesn't make sense to me why a default OneOrMany<int> actually has anything at all. I'm not sure if it is like this due to the previous implementation (by holding a single item value of T which would not be null for value types) or if it was intentional.

We use nullable types like `OneOrMany<int?>`. So is this really a concern?

**Comment by RehanSaeed** [comment]
> I've been looking at further performance and allocation optimisations - one that I have been messing with is making OneOrMany only internally hold an array rather than an array and a single item.

It holds a single item and a `List<T>` at the moment. Given it's a `readonly struct`, it can totally be turned into an array. I guess a `List<T>` was used without much thought to allocations at the time.

**Comment by Turnerj** [comment]
> We use nullable types like OneOrMany<int?>. So is this really a concern?

My concern really came down to updating tests to conform with this behaviour rather than making the new code behave in the same manner. But yeah, Schema.NET doesn't actually rely on plain value types so fixing that behaviour should be a good thing.

> It holds a single item and a List<T> at the moment. Given it's a readonly struct, it can totally be turned into an array. I guess a List<T> was used without much thought to allocations at the time.

Yeah definitely - `List<T>` was a good basis for it and made a lot of things simpler. Its nice to avoid when you can but honestly, half the time is just getting the functionality to behave like you want. 😂

**Comment by Turnerj** [comment]
I'll get these changes sorted tomorrow and after that - I reckon we are good for a new release!

**Comment by RehanSaeed** [comment]
> My concern really came down to updating tests to conform with this behaviour rather than making the new code behave in the same manner. But yeah, Schema.NET doesn't actually rely on plain value types so fixing that behaviour should be a good thing.

So it's for completeness. Fair enough.

> Yeah definitely - List<T> was a good basis for it and made a lot of things simpler. Its nice to avoid when you can but honestly, half the time is just getting the functionality to behave like you want. 😂

That's half the battle!

> I'll get these changes sorted tomorrow and after that - I reckon we are good for a new release!

Nice. You've pretty much driven this release forward.

**Comment by Turnerj** [comment]
Fixed in #118

**Comment by RehanSaeed** [comment]
@Turnerj Is now a good time for a release or do you have anything else up your sleeve?

**Comment by RehanSaeed** [comment]
@Turnerj Is now a good time for a release or do you have anything else up your sleeve?

**Comment by Turnerj** [comment]
I reckon let's do a release now. If I do throw together any new PRs, they can always be for the version after in a few weeks/months etc.

**Comment by RehanSaeed** [comment]
Released 7.0.0

https://github.com/RehanSaeed/Schema.NET/releases

**Comment by RehanSaeed** [comment]
That should be named the @Turnerj release. Thanks for pushing the project forward. It was good to get more eyes on it and clean up some more subtle bugs in particular.
