### ISSUE TITLE
Microsoft.VisualStudio.Threading.Analyzers gets added to dependent projects

### ISSUE THREAD

**Issue by csdecrypt** [RehanSaeed/Schema.NET#123]
### Describe the feature
Hi

The analyzer Microsoft.VisualStudio.Threading.Analyzers is automatically added to projects that use Schema.NET.

Altough i really like that analyzer, i'd rather not force consumers of this library to use it too.

(Src: https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#dependent-projects)

**Comment by Turnerj** [comment]
Fixed in #124

**Comment by RehanSaeed** [comment]
Thank you. I guess I missed that.

**Comment by RehanSaeed** [comment]
I'll do a release soon.

**Comment by RehanSaeed** [comment]
Released in https://github.com/RehanSaeed/Schema.NET/releases/tag/Schema.NET.7.0.1. CI builds will push to NuGet soon.
