### ISSUE TITLE
Upgrading to Schema.org Release 7.0 - Issues with extending primitives

### ISSUE THREAD

**Issue by Turnerj** [RehanSaeed/Schema.NET#126]
On the 21st of January, the next version of Schema.org has been released. I was going to open a PR to upgrade to however there seems to be some issues with the tool that I'm not sure how to handle - some of the problem might actually be a bug from Schema.org but at this stage, let's just look at it in scope of this project.

There is a new type called `PronounceableText`. While [this type is (apparently) pending](https://schema.org/PronounceableText), the schema tool doesn't see it as pending. Additionally though, this is a type that extends a primitive which doesn't seem supported. (Of note, `PronounceableText` itself isn't classified as a primitive even though it extends `Text` which is)

When running the tool, it trips this exception when processing `PronounceableText`:
https://github.com/RehanSaeed/Schema.NET/blob/00cf92193d4dc4e235c0b585b60594fdbe25e83b/Tools/Schema.NET.Tool/Services/SchemaService.cs#L174-L178

In one way, if this type is pending it shouldn't even hit here. If it is technically marked correctly but the website is wrong saying it is pending, we need to work out how to handle types that extend primitives.

Should primitive types be "real" types in Schema.NET? For example, we could have a `Text` type (with no interface) and have it implicitly convert to/from string? That way, we could build `PronounceableText` on top of it? It should allow all our `Values<>` and `OneOrMany<>` implicit things to still work with concrete types etc. We'd probably want the primitive types to be `struct` though to help avoid additional allocations when dealing with numbers and dates (which would also likely follow this pattern).

I'm thinking unless we are going to ignore this primitive, we might need to do a bit of an overhaul of the schema tool.

What are your thoughts on this?

**Comment by RehanSaeed** [comment]
There is a mapping between Schema.org primitive types and C# types:

There is an `IsPrimitive` method in [SchemaClass.cs](https://github.com/RehanSaeed/Schema.NET/blob/00cf92193d4dc4e235c0b585b60594fdbe25e83b/Tools/Schema.NET.Tool/Models/SchemaClass.cs#L26) and a `GetCSharpTypeStrings` method in [SchemaService.cs](https://github.com/RehanSaeed/Schema.NET/blob/00cf92193d4dc4e235c0b585b60594fdbe25e83b/Tools/Schema.NET.Tool/Services/SchemaService.cs#L303).

In the case of `PronounceableText`, I guess we'd just represent it as a `string`. I'm glad I added that `CheckThatNewPrimitiveTypeNotAdded` exception :).

We parse two JSON-LD files downloaded from Schema.org to generate all our types. Unfortunately, they sometimes have bugs in their schema. If you look at their GitHub issues, there are hundreds of open issues, so very difficult for them to get ahead. One of the bugs I've seen is pending types ending up in the production schema or they are not marked as pending (I can't remember how it was structured).

As for your idea to make a `Text` type, I have certainly thought of it. I'm not sure about the benefit over what is there now i.e. a mapping between C# types and primitive types in schema.org, apart from being more 'correct'. Do you see some advantage, I've missed?

**Comment by Turnerj** [comment]
Ahhhh, good to know it might be a bug on their end. I mean, it isn't good that they might have a bug... but you know what I mean. 😉

Prior to this `PronounceableText` type, I probably wouldn't have thought there would be any benefit - I like dealing with the native types. The thing is, `PronounceableText` actually has properties of its own - combine that with it inheriting from the `Text` primitive, I can't see an easy way to support it "generically" in the future without explicitly defining `Text` type.

That said, we may still hit weird things like how `Url` is a type that extends `Text` but we already have a great native type of `Uri` which does everything we'd really want.

You're thinking though, just add it as another "case" to go to the C# string type in that `GetCSharpTypeStrings` method?

**Comment by Turnerj** [comment]
Hey @RehanSaeed - you might have implied it in your previous comment but just want to confirm, are you suggesting (for now at least) we just add `PronounceableText` as another case-statement to bind to the string type in `GetCSharpTypeStrings`?

I'm happy to do that, just want to make sure we're on the same page. 🙂

**Comment by RehanSaeed** [comment]
Yes, that is indeed what I meant.

**Comment by RehanSaeed** [comment]
Sorry, just realized I didn't reply this this issue.
