### ISSUE TITLE
BusinessFunction enum missing values

### ISSUE THREAD

**Issue by markcoole** [RehanSaeed/Schema.NET#133]
### Describe the bug

There are currently no values inside the BusinessFunction enum. When using the default value this results in an error. 

I've seen this has been previously raised (https://github.com/RehanSaeed/Schema.NET/issues/60) but because there's no open ticket I am creating one so I can fork and add a PR.

### To Reproduce

Using the below code causes an error:

`
Offers = new Offer()
                {
                    BusinessFunction = new OneOrMany<BusinessFunction?>(new BusinessFunction() { }),
                }`

### Expected behaviour

Enum has values as described at: https://schema.org/BusinessFunction

Might be as simple as adding this to the BusinessFunction Enum

       `/// <summary>
        /// Indicates that the value is Sell.
        /// This is the default value.
        /// </summary>
        [EnumMember(Value = "http://purl.org/goodrelations/v1#Sell")]
        Sell,

        /// <summary>
        /// Indicates that the value is Buy.
        /// </summary>
        [EnumMember(Value = "http://purl.org/goodrelations/v1#Buy")]
        Buy,

        /// <summary>
        /// Indicates that the value is ConstructionInstallation.
        /// </summary>
        [EnumMember(Value = "http://purl.org/goodrelations/v1#ConstructionInstallation")]
        ConstructionInstallation,

        /// <summary>
        /// Indicates that the value is ConstructionIDisposenstallation.
        /// </summary>
        [EnumMember(Value = "http://purl.org/goodrelations/v1#Dispose")]
        Dispose,

        /// <summary>
        /// Indicates that the value is LeaseOut.
        /// </summary>
        [EnumMember(Value = "http://purl.org/goodrelations/v1#LeaseOut")]
        LeaseOut,

        /// <summary>
        /// Indicates that the value is Maintain.
        /// </summary>
        [EnumMember(Value = "http://purl.org/goodrelations/v1#Maintain")]
        Maintain,

        /// <summary>
        /// Indicates that the value is ProvideService.
        /// </summary>
        [EnumMember(Value = "http://purl.org/goodrelations/v1#ProvideService")]
        ProvideService,

        /// <summary>
        /// Indicates that the value is Repair.
        /// </summary>
        [EnumMember(Value = "http://purl.org/goodrelations/v1#Repair")]
        Repair,`

But I haven't been able to fork and get the package to work in my project. 

### Schema Objects

Which [schema.org](https://schema.org) object is this about if any?

https://schema.org/BusinessFunction

**Comment by RehanSaeed** [comment]
This project downloads some JSON from schema.org and generates all C# classes. Last time I checked, unfortunately the `BusinessFunction` enum values are not in that feed but come from `purl.org`.

If you want to add them, we could either figure out if `purl.org` has another feed we can also read or create a [custom override](https://github.com/RehanSaeed/Schema.NET/tree/master/Tools/Schema.NET.Tool/CustomOverrides) in our tool to just manually add these values to the `BusinessFunction` enum.

**Comment by RehanSaeed** [comment]
Closing for now. Feel free to come back and re-open if you have more input.
