### ISSUE TITLE
Setting an "incomplete" date for a Date/DateTime property

### ISSUE THREAD

**Issue by tiaochuan** [RehanSaeed/Schema.NET#15]
I am trying to set just the Year for CreativeWork,dateCreated property. But since in Schema.NET, the dateCreated is of DateTimeOffset data type, it is impossible to do so.

Based on Schema.org/Date, the date format should follow ISO8601 (http://en.wikipedia.org/wiki/ISO_8601), which basically, allows "yyyy" format.

“ISO 8601 prescribes, as a minimum, a four-digit year [YYYY]…”

The same can also be referenced in https://www.w3.org/TR/NOTE-datetime.

Any help would be greatly appreciated.

**Comment by RehanSaeed** [comment]
One solution for solving this is for every date property e.g.

`public OneOrMany<DateTimeOffset?>? DateCreated { get; set; }`

We also create a format property that determines how the date is serialized e.g.

`public string DateCreatedFormat { get; set; }`

The format can be set to `yyyy` or any other date format `yyyy MM dd HH:mm:ss` and will determine what is serialized/deserialized.

**Comment by tiaochuan** [comment]
Just a suggestion, what if we define a new “datetime” class, say ISO8601DateTime, which a constructor that can accept (int? Year, int? Month, int? Day, int? Hour, int? Minute, int? Second)? 😁

**Comment by RehanSaeed** [comment]
Yes, that might be a better idea. We could add an implicit conversion from `DateTimeOffset` to `ISO8601DateTime` too, so you could keep using `DateTimeOffset` if you wanted to.

**Comment by tiaochuan** [comment]
I need advice on how to serialize `ISO8601DateTime` object into just the date string? Can somebody point me to the right direction? 😁

**Comment by RehanSaeed** [comment]
This is what my `ISO8601DateTime` class might look like:

```
public enum ISO8601DateTimeFormat
{
    Date,
    DateTime
    DateTimeOffset
}

public struct ISO8601DateTime
{
    public readonly DateTimeOffset dateTimeOffset;
    public readonly ISO8601DateTimeFormat format;

    public ISO8601DateTime(DateTimeOffset dateTimeOffset, ISO8601DateTimeFormat format)
    {
        this.dateTimeOffset = dateTimeOffset;
        this.format = format;
    }

    // TODO: Add other constructors for DateTime, etc.

    // TODO: Add implicit conversion operator methods so I can convert `DateTimeoffset` and `DateTime` to `ISO8601DateTime` without calling the constructor.

    // TODO: Implement Equals, ToString, GetHashCode, IEquatable, IEquatable<T>, IComparable, IComparable<T>
}
```

**Comment by RehanSaeed** [comment]
Schema.org Date type is now support using .NET `int` and `DateTime` types which are serialized to `YYYY` and `YYYY-MM-dd` respectively.
