### ISSUE TITLE
Unrelated `covid-19` topic used in project

### ISSUE THREAD

**Issue by alagos** [RehanSaeed/Schema.NET#153]
I don't get what does has to do this project with Coronavirus
![Captura de pantalla_2020-03-29_09-15-16](https://user-images.githubusercontent.com/475834/77845406-36557b80-720b-11ea-8e0c-01f4ea037a27.png)
If is just to attract interest using a trendy tag... ok, you did it :clap:

**Comment by RehanSaeed** [comment]
This project contains new schema.org v7 types for the Corona virus.

**Comment by Tiggerito** [comment]
Some more information on this:

https://blogs.bing.com/webmaster/march-2020/Bing-adopts-schema-org-mark-up-for-Special-Announcements-about-COVID-19

**Comment by RehanSaeed** [comment]
Thanks @tiggerito.
