### ISSUE TITLE
Potential XSS vulnerability

### ISSUE THREAD

**Issue by benmccallum** [RehanSaeed/Schema.NET#18]
I think that a lot of people in the ASP.NET MVC world would do something like this to get their schema rendered.

```
<script type="application/ld+json">
    @Model.myThing.ToString();
</script>
```

Problem is with `Json.Convert`'s default settings, that opens up an XSS vulnerability if the data put in a thing's property was untrusted. e.g. a business name on your website could be user-supplied by that business, and they could make their business name `</script><script>alert('gotcha');</script>`.

I think it would be addressed by updating the default Serialization settings in Thing.cs to include `StringEscapeHandling = StringEscapeHandling.EscapeHtml`, but this isn't my area of expertise. That also  might be a breaking change if HTML is allowed in any schema properties?

What do you think? Just opening it up for discussion as trying to avoid this in my own project.

**Comment by RehanSaeed** [comment]
Thanks for the suggestion, I think you are correct in your thinking. Security should be a default. I'd be happy to take a PR with this change. It would be breaking so, it'd be a major version change.

**Comment by benmccallum** [comment]
Sure thing, I'll whip one up when I get a sec.

**Comment by RehanSaeed** [comment]
Will get released soon.
