### ISSUE TITLE
Properties assigned `null` are rendered by ToString()

### ISSUE THREAD

**Issue by benmccallum** [RehanSaeed/Schema.NET#20]
Even though the `JsonSerializerSettings` specify `NullValueHandling = NullValueHandling.Ignore` if you assign a null to a property it'll start coming out in the serialized response. 

I believe this is because the property is no longer null, but a `Values<T>` wrapping the null, which has `HasValue = false`.

Added a unit test to check this locally, on master, but then realised it's not an issue in master, so I'm guessing there's some unreleased changes in master, perhaps part of the PR around multiple types in properties?

**Comment by RehanSaeed** [comment]
Updated master. Try now.

**Comment by benmccallum** [comment]
Hey mate, bit confused by your comment. It was a non-issue in master, but an issue in the latest nuget package. Doesn't look like you've released a new version. I'll pull latest master and confirm again anyway. Prob submit a PR with the new unit test too.

**Comment by benmccallum** [comment]
Cool, refreshed my #19 from master, added unit test in there to prevent any regression on this and this can be closed out once you've released to nuget.

**Comment by RehanSaeed** [comment]
I haven't released a new version. Wanted to get your change in first.

Will take a look.

**Comment by RehanSaeed** [comment]
Is this still an issue?

**Comment by benmccallum** [comment]
Nope. Can be closed. Cheers.

**Comment by RehanSaeed** [comment]
FYI, just released. Will take a min to get onto NuGet.
