### ISSUE TITLE
Add VirtualLocation type

### ISSUE THREAD

**Issue by pinkplus** [RehanSaeed/Schema.NET#203]
### Describe the feature

It looks that the VirtualLocation type is added to schema.org recently. Can we get it added to the library?

### Schema Objects

Which [schema.org](https://schema.org) object is this about if any?

https://schema.org/VirtualLocation

**Comment by RehanSaeed** [comment]
From schema.org:

> This term is proposed for full integration into Schema.org, pending implementation feedback and adoption from applications and websites.

We don't generate code for pending types at the moment.

**Comment by pinkplus** [comment]
OK, I understand it's still a pending type.

Google says it wants us to use the VirtualLocation type for online events though. From [Google's doc](https://developers.google.com/search/docs/data-types/event#structured-data-type-definitions):

> You can start using the VirtualLocation type even though it's still pending on schema.org.

Is there a workaround that I can use?

**Comment by RehanSaeed** [comment]
Wow, ok. I can see why that is a major problem.

I've thought about adding all Pending types in the past but the assembly would get much larger with so many extra types and there would be a lot of breaking changes between versions.

If you want a solution right now, we support creating your own custom types using inheritance.

I'm not sure about a longer term solution just yet. I'd want to check the schema.org git repo to see what's going on with this type. It may be that it's just about to be officially released. Then we just need to wait a bit.

**Comment by pinkplus** [comment]
Yeah, let me try inheriting for now.

Regarding the long term solution, what if we can put the pending types into a separate assembly? The main assembly size won't be so big. People can get the pending assembly only when they need it. Not sure about breaking changes though... Maybe we have to say that the types can different because they are not finalized.

**Comment by danhickman** [comment]
First off, thanks for the library.  Big time saver.  I would also like to see https://schema.org/VirtualLocation and the related https://schema.org/eventAttendanceMode property added ASAP.  This has quickly become important because of the COVID-19 situation so a quick response to adding these would be appreciated.

As for creating a custom type inheritance, in order to use a custom VirtualLocation as the Event.location property, what class would it need to inherit from?  Does anything custom need to be implemented to ensure the serialization will be performed correctly on the custom class?  Do you have an example of this?

**Comment by Turnerj** [comment]
> @pinkplus : Regarding the long term solution, what if we can put the pending types into a separate assembly? The main assembly size won't be so big. People can get the pending assembly only when they need it. Not sure about breaking changes though... Maybe we have to say that the types can different because they are not finalized.

I do like the idea of pending types in a separate assembly as it both allows the use of them but also indicates that they are still pending so things might change. We'd have to do a bit of work with how our tooling generates the classes to define that split though which is a bit of a big project. There are plans to do some larger work to the tooling (moving to C# Source Generators) which may make this process a lot easier though that is still a while away.

That said, the next bit is important in your case too...

> @danhickman : As for creating a custom type inheritance, in order to use a custom VirtualLocation as the Event.location property, what class would it need to inherit from? Does anything custom need to be implemented to ensure the serialization will be performed correctly on the custom class? Do you have an example of this?

There is technically support for inherited types though depending on how you use it. I think you will have issues with `VirtualLocation` though as `Event.Location` supports only these types: `IPlace`, `IPostalAddress`, `string`. You don't have control of that. This can be one of the issues with trying to add support for pending types when they introduce changes to existing types.

So to use a custom `VirtualLocation` on that property, you'd need to unfortunately implement `IPlace` (and most likely inherit `Place` unless you want to implement all the properties yourself). After getting past that hurdle, make sure to decorate your custom properties like so (taken from `Place` as an example):

```csharp
/// <summary>
/// The fax number.
/// </summary>
[DataMember(Name = "faxNumber", Order = 114)]
[JsonConverter(typeof(ValuesJsonConverter))]
public OneOrMany<string> FaxNumber { get; set; }

/// <summary>
/// The geo coordinates of the place.
/// </summary>
[DataMember(Name = "geo", Order = 115)]
[JsonConverter(typeof(ValuesJsonConverter))]
public Values<IGeoCoordinates, IGeoShape> Geo { get; set; }
```

`DataMember` is used to specify the property name during serialization. The order shouldn't be necessary on your end (and we will actually lose the order once we've moved to System.Text.Json). However the `JsonConverter` is extremely important - you need to specify this so we can convert to and from the various different properties for you.

With all this done, creating your custom `VirtualLocation` and setting it on the `Event.Location` property should work fine for serialization.

Deserialization on the other hand is a much more complicated story. Have a look at the thread from [this comment down](https://github.com/RehanSaeed/Schema.NET/pull/109#issuecomment-653611416) to understand what some of our issues are with deserialization. The short version is: We can't easily determine the deserialization take from the "@type" property for custom types.

**Comment by RehanSaeed** [comment]
I'd be happy with a new `Schema.NET.Pending` NuGet package containing all the pending types. I'd be happy to take a PR for that work.

The only major downside I can see is that the pending types are liable to change a lot and so we'd have to push out package updates quite frequently to keep up. I'm not sure that we'd do it often enough.

It's probably also worth you pushing for the types you want to be moved from pending to release in the upstream schema.org project itself. There's probably an open issue about these types already. Especially, if Google use these types.

**Comment by RehanSaeed** [comment]
No, not yet. I'd be happy to take a PR for it.

**Comment by danhickman** [comment]
@RehanSaeed can we move forward on the separate Schema.NET.Pending package ASAP?  This is really needed by the community.

**Comment by RehanSaeed** [comment]
I don't currently have bandwidth to work on this feature. However, I'd be willing to take a PR that creates a new `Schema.NET.Pending` project and modifies Schema.NET.Tool to spit out all pending types into that project. As @Turnerj talks about, I think we should avoid adding pending properties to production/released types.

**Comment by Turnerj** [comment]
Hey @pinkplus , @danhickman , @cduivis - I know it has been a while since this was discussed but I wanted to let you know that we've released Schema.NET.Pending on NuGet now which has all the properties and types (both pending and not). You can reference this instead of Schema.NET.

**Comment by danhickman** [comment]
@Turnerj much appreciated.  I'll be utilizing it for sure.

**Comment by pinkplus** [comment]
Thanks @Turnerj!
