### ISSUE TITLE
Renaming master Branch to main

### ISSUE THREAD

**Issue by RehanSaeed** [RehanSaeed/Schema.NET#219]
The default branch name for GitHub and Git has changed to `main`. To avoid having to remember the default branch name and also for ethical reasons, I propose renaming the `master` branch to `main`.

More info here:
https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main

**Comment by RehanSaeed** [comment]
cc @Turnerj

**Comment by Turnerj** [comment]
Yep, all good with me. I didn't know that GitHub has changed the default too - that is cool.
