### ISSUE TITLE
ToString() and ToHtmlEscapedString() result in a single line 

### ISSUE THREAD

**Issue by picasso566** [RehanSaeed/Schema.NET#229]
First, thanks for the library! Shaved a good amount of time on this project I'm on!

This is only an annoyance and I may be missing something on my end, but when I dump out the JobPosting object in a Razor view:
```
        <script type="application/ld+json">
            @Html.Raw(jobJSON.ToString().Replace("\\r\\n", ""))
        </script>
```
I end up everything in a single line:
{"@context":"https://schema.org","@type":"JobPosting","title":"Citrix Virtual Desktop Engineer","description":"<p>A global life insurance firm is hiring&nbsp;a&nbsp;desktop engineer.&nbsp;</p><p>&nbsp;</p><p>This is a wonderful opportunity to wo

Just makes it difficult to debug. Please let me know if there's a flag somewhere or something I can do to get formed json with line breaks. Thanks

**Comment by picasso566** [comment]
I want to be clear too, that .Replace("\\r\\n", "") is for actual \r\n characters in the description text fields. Removing that does nothing to format the json.

**Comment by RehanSaeed** [comment]
We should probably allow you to pass custom `JsonSerializerSettings` to the `ToString()` method as an overload or alternatively pass in a boolean to enable/disable formatting.

@Turnerj has a PR up to switch from `Newtonsoft.Json` to `System.Text.Json`. We should probably wait for that to go in first if we decide to go with the former.

For now, you can serialize the type yourself. Take a look at `SchemaSerializer` for how.

**Comment by Turnerj** [comment]
We actually do have an overload of `ToString` for passing `JsonSerializerSettings` already:

https://github.com/RehanSaeed/Schema.NET/blob/b9db142d3f32a832337e370549e46dd64a77c1b2/Source/Schema.NET/Thing.Partial.cs#L42-L43

When we do finish the transition to S.T.J, this overload will till exist but use the `JsonSerializerOptions` type from S.T.J instead.

**Comment by RehanSaeed** [comment]
Apologies, I scanned that file and didn't spot the overload. I thout I'd remembered seeing it.

I think we can close this then.

**Comment by picasso566** [comment]
Thank you all for such a quick response. I'm in Tokyo and been working long hours on something, so it seems like in 2 days you  all responded and answered my questions with notes about future changes.

**Just a note**
There is one thing to note, it's quite probably the newtonsoft implementation/version I have installed but if I set the Formatting, the NullValueHandling stops working.
```
JobPosting posting = GetJobPostingSchema(language, model);
return posting.ToString(new JsonSerializerSettings() { Formatting = Formatting.Indented, NullValueHandling = NullValueHandling.Ignore });
```
The json indentation is right, but every null value in a Schema.org JobPosting object is also output. Which is more annoying for debugging than the entire thing being in one line. So I will put it back to the way it was for now. I do not have time atm to sort out the libraries. 

Thanks again for you help!

**Comment by Turnerj** [comment]
Hmmm, you may need to include `DefaultValueHandling = DefaultValueHandling.Ignore`. 
Here is our default serialization settings where we also have that property set:

https://github.com/RehanSaeed/Schema.NET/blob/b9db142d3f32a832337e370549e46dd64a77c1b2/Source/Schema.NET/SchemaSerializer.cs#L24-L50

Hope that helps!

**Comment by picasso566** [comment]
And that was exactly what I needed! 
I was about to go fishing around in the source but didn't have time. Thanks for pointing right to it!
