### ISSUE TITLE
Issue with HowTo schema

### ISSUE THREAD

**Issue by eduardomc** [RehanSaeed/Schema.NET#270]
I'm trying to build a HowTo schema like this:

```
var howToSchema = new HowTo()
{
    Name = "some name",
    Description = "some desc"                            
};

var step1 = new HowToStep()
{
    Url = new Uri("http://example.com#step1"),
    Name = "Name for step1",
    Text  = "Desc for step1",
    Position = 1
};

var step2 = new HowToStep()
{
    Url = new Uri("http://example.com#step2"),
    Name = "Name for step2",
    Text  = "Desc for step2",
    Position = 2
};

//Here is the issue
//howToSchema.Step property is of type Values<ICreativeWork, IHowToSection, IHowToStep, string>
//I cannot add more than one step, which is the main purpose of the how to element
howToSchema.Step = step1;
howToSchema.Step = step2;
```

The issue is that I cannot add more than one step.

For reference, google has some examples and the howTo schema has a 'step' array. Here is the link: https://developers.google.com/search/docs/data-types/how-to#standard

**Comment by eduardomc** [comment]
Oh nevermind... I just noticed Values can accept an array of IHowToStep items

**Comment by Turnerj** [comment]
Glad you were able to work this out yourself @eduardomc ! But yeah, you can use a list or an array and set it to the property - it will automatically convert to the `OneOrMany<T>` or `Values<T, ...>` type as appropriate.
