### ISSUE TITLE
Investigate System.Text.Json Source Generators

### ISSUE THREAD

**Issue by RehanSaeed** [RehanSaeed/Schema.NET#321]
System.Text.Json in .NET 6 added source generator support. Investigate if this can help improve performance.

https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/

**Comment by Turnerj** [comment]
We already have this covered by #310 🙂

**Comment by Turnerj** [comment]
But how good does that performance look in that .NET 6 performance blog post?!

**Comment by RehanSaeed** [comment]
lol, I forgot I raised that! Yeah was just reading that post....so long.
