### ISSUE TITLE
The type 'System.Object' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by lorenpaulsen** [RehanSaeed/Schema.NET#33]
I had a difficult time integrating this library into a .NET 4.7.2 / MVC 5 application, due to the following exception I was receiving on my cshtml page at runtime.

```
The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

It turns out that is is due to the project specifying `<TargetFrameworks>netstandard1.1;netstandard2.0</TargetFrameworks>` instead of `<TargetFrameworks>netstandard1.1;netstandard2.0;net452</TargetFrameworks>`.

In a previous rejected pull request you mention:

> This project supports `netstandard1.1` and `netstandard2.0` which means that .NET 4.5.2 is already supported.
> 
> Feel free to reopen if I've missed something.
> 
> _Originally posted by @RehanSaeed in https://github.com/RehanSaeed/Schema.NET/pull/27#issuecomment-443424436_

While this is technically true, it requires an unintuitive workaround in my web.config as follows:

```
<compilation debug="true" targetFramework="4.7.2">
  <assemblies>
    <add assembly="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"/>
  </assemblies>
</compilation>
```

Which I finally found from this thread: https://github.com/dotnet/standard/issues/542

Anyway, I just wanted to help out anyone else that may run into this issue in the future.

**Comment by RehanSaeed** [comment]
Is adding `net452` really the only solution? Some people in that long thread mention updating to the latest version of Visual Studio, does that work?

**Comment by RehanSaeed** [comment]
Looks like it is: https://weblog.west-wind.com/posts/2019/Feb/19/Using-NET-Standard-with-Full-Framework-NET

The above post suggests that 4.7.2 should work as advertised though. It's only older .NET Frameworks that need net46. I'll accept a PR for that.

**Comment by lorenpaulsen** [comment]
My ASP.NET project was already targeting .NET 4.7.2 and I was using the latest Visual Studio. As your links mention, .NET 4.7.2 is the first version to implement .NET Standard 2.0, and thus no additional assemblies are needed to compile.

The exception I'm encountering, however, is runtime, and an additional web.config workaround is necessary even with .NET 4.7.2. Would you like me to send you a simple repro?

**Comment by RehanSaeed** [comment]
Ok, it sounds like we should just add net46 as a target framework. Willing to take a PR for that.

**Comment by RehanSaeed** [comment]
Added `net461` target.

**Comment by lorenpaulsen** [comment]
Thanks, I just updated to 4.2.0 and can confirm that the original workaround is no longer necessary. It's not too bad of workaround, but it's definitely easier to integrate when no unexpected changes are required.
