### ISSUE TITLE
TimeSpan for OpeningHours?

### ISSUE THREAD

**Issue by silvereh** [RehanSaeed/Schema.NET#38]
I was wondering why implementing the Opens and Closes attributes of OpeningHoursSpecification as a TimeSpan, it seems counterIntuitive given this data is supposed to represent an hour when a business or place opens or closes. 

As a result, I don't know how to implement it in my project, I thought it would be more logical to use a DateTime.

Would you have some explanation that would help me understand it better and use it correctly?

Thanks in advance

**Comment by RehanSaeed** [comment]
See https://schema.org/Time

`TimeSpan` fits best.

**Comment by silvereh** [comment]
Isn't a TimeSpan a duration rather than a specific point in time, which the Time element is?

**Comment by RehanSaeed** [comment]
The format is `hh:mm:ss` which fits `TimeSpan` best. `DateTime` has the date component which doesn't make sense.
