### ISSUE TITLE
Wrong type for Book.Author ("Persona" become an "Organization") after deserialization

### ISSUE THREAD

**Issue by radetskyi** [RehanSaeed/Schema.NET#39]
**[Author](https://schema.org/author) deserialization issue**

Just run into situation:

for [Book](https://schema.org/Book) I have a list of [Author](https://schema.org/author) type of [Person](https://schema.org/Person)

~~~ json
...
"author": [
        {
            "@type": "Person",
            "name": "SomeName",
            "description": "SomeDescription.md",
            "image": "SomeImage",
            "url": "https://someUrl.me",
            "email": "someemail@gmail.com",
            "jobTitle": "CEO SomeCompany Solutions"
        },
        {
            "@type": "Person",
            "name": "Иван Васильевич",
            "image": "Images/Иван Васильевич.jpg",
            "email": "car.kreml@yandex.ru",
            "jobTitle": "просто Царь"
        }
    ]
...
~~~

the way I`m deserialize:
~~~ c#
public static Book GetMetadata(string path)
        {
            var file = Path.Combine(path, FileNames.Metadata);
            if (File.Exists(file))
            {
                var json = File.ReadAllText(file);
                Book bookMetadata = JsonConvert.DeserializeObject<Book>(json) as Book;
                return bookMetadata;
            }
            else
                throw new ArgumentNullException("Metadata file is missing.");
        }
~~~

but after deserialization of my "schema.json" into c# class I got field "Author" type of [Organization](https://schema.org/Organization). Any other fields like "JobTitle" are ignored.

![image](https://user-images.githubusercontent.com/15612415/56391110-5ed0a980-6236-11e9-85df-b010fc8fa9cc.png)

**Comment by RehanSaeed** [comment]
Could you write a failing unit test and submit it as a PR? It'd make diagnosis easier.

**Comment by RehanSaeed** [comment]
Fixed in https://github.com/RehanSaeed/Schema.NET/releases/tag/Schema.NET.3.7.1.

Thanks again!
