### ISSUE TITLE
How to set value for AcceptedPaymentMethod on Offer?

### ISSUE THREAD

**Issue by MEmanuelsson** [RehanSaeed/Schema.NET#42]
On an Offer-object I'm trying to set a value on AcceptedPaymentMethod using the enum PaymentMethod but can't figure out how that's possible to do since that enum is empty? Any suggestion about how to do this?

**Comment by RehanSaeed** [comment]
Most likely this is a bug. Could also be bad JSON from schema.org.

**Comment by RehanSaeed** [comment]
Turns out it's a bug in the schema.org JSON that I use to generate the classes. Nothing I can do. Please raise a GitHub issue with schema.org.

**Comment by RichardWallis** [comment]
@RehanSaeed Can you share your analysis of the bug in the schema.org JSON that you use to generate classes.

Also, how are you importing the JSON-LD, from a download file or via content negotiation?

**Comment by RehanSaeed** [comment]
Responded on linked issue.
