### ISSUE TITLE
Missing jobTitle on Person

### ISSUE THREAD

**Issue by aKzenT** [RehanSaeed/Schema.NET#423]
### Describe the bug

JobTitle property is missing on Person ( https://schema.org/jobTitle ). It was present in version 8, but disappeared in verison 9. I did not find any reason why it's missing now.

### Steps to reproduce

Look for Person.JobTitle

### Expected behaviour

JobTitle exists on class Person

### Schema objects

https://schema.org/Person
https://schema.org/jobTitle

**Comment by aKzenT** [comment]
Got it. The confusing thing for me is that it was present in previous versions of the library and now disappeared which breaks our code using the property. So was there a change in how pending properties are handled in Schema.NET?

**Comment by RehanSaeed** [comment]
Not that I'm aware of. The change can also come from schema.org itself sometimes as they are constantly changing schemas.

You can always use the Pending package to workaround the issue temporarily.

**Comment by Turnerj** [comment]
There may have been an issue where pending properties (in some cases) were included but not pending types (or properties that depended on those types). That would have been a little while back though...

**Comment by kahlan88** [comment]
Are there any updates on this please? It's been in schema.org for over a year now, it seems and it would be great to have this available.

**Comment by Turnerj** [comment]
So the main thing with this issue as far as I could tell was that the schema.org JSON-LD file we parse to generate the library didn't have `jobTitle` correctly in that specific version - either some other flag on the data or missing it etc that prevented generation.

Regarding pending properties - anything marked in blue on the schema.org site (like how `jobTitle` still is at the time of writing) is a pending property. Pending properties may have pending types (also in blue). We only ship pending properties and types in the Schema.NET.Pending library with everything else shipped in Schema.NET directly.

In the latest release of Schema.NET.Pending (v13.0.0), I do see the `jobTitle` property there with the pending type `DefinedTerm` also in it.
