### ISSUE TITLE
Special structs for Date and DateTime

### ISSUE THREAD

**Issue by MEmanuelsson** [RehanSaeed/Schema.NET#46]
I raised this issue (https://github.com/schemaorg/schemaorg/issues/2240) on the schemaorg github repo yesterday regarding how to handle Date which only consists of a year in the Schema.NET implementation of schemaorg. Following the comment from RichardWallis I believe it would be a good idea to create special structs to handle Date and DateTime in the schemas where these are applicable since DateTimeOffset (now being used) always contains a complete date and time. Any thoughts around this?

**Comment by RehanSaeed** [comment]
Interesting question. .NET doesn't have a good Date/Time classes and has never been good at representing dates without time. One approach I have taken is to use `DateTimeOffset` for dates with time and then `DateTime` for just dates (making sure that JSON serializes as just the date portion). That still wouldn't help with representing a year which I think we could represent as a single `int` number.

**Comment by RehanSaeed** [comment]
If you're passionate about date representation, I'll be willing to accept a PR for this work.

**Comment by MEmanuelsson** [comment]
Working on a pull request right now which you'll receive shortly. Focusing on Date and not DateTime, since they seem to be rendered correctly as far as I can tell.

**Comment by RehanSaeed** [comment]
Ok cool!

I think when we use DateTime, we should serialize it as a date without time portion using a JSON.NET attribute. See https://stackoverflow.com/questions/16320762/dates-without-time-in-asp-net-web-apis-json-output

**Comment by MEmanuelsson** [comment]
OK, not really sure about how that would be possible to use for "dates" that consist of only the year or the year and month as explained on https://github.com/schemaorg/schemaorg/issues/2240?

**Comment by MEmanuelsson** [comment]
Pull request created #48

**Comment by RehanSaeed** [comment]
Thanks for this. Reviewed it. I think you are on the right track.

**Comment by RehanSaeed** [comment]
This is now fixed. Thanks again @MEmanuelsson!
