### ISSUE TITLE
Support Deserializing @language inside @context Object

### ISSUE THREAD

**Issue by beppe9000** [RehanSaeed/Schema.NET#63]
- [LocalBusiness](https://schema.org/LocalBusiness)

I get an exception from JsonConvert when I do this. The result is null.
`Newtonsoft.Json.JsonConvert.DeserializeObject(Of Schema.NET.LocalBusiness)(json)`

This is the exception: 
```
Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: [. Path '@context', line 4, position 16.'
```

This is the json I'm working with... Is there a syntax error somewhere?

```
{
  "@context" : [ "http://schema.org", {
    "@language" : "it"
  } ],
  "@type" : "LocalBusiness",
  "name" : "Mario Rossi",
  "url" : "https://example.com/mario-rossi-srl",
  "@id" : "https://example.com/mario-rossi-srl",
  "legalName" : "Mario Rossi s.r.l.",
  "currenciesAccepted" : "EUR",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Venezia",
    "addressRegion" : "VN",
    "postalCode" : "00334",
    "streetAddress" : "10, Piazza Grande"
  },
  "contactPoint" : [ {
    "@type" : "ContactPoint",
    "contactType" : "customer service",
    "telephone" : "+393332234666"
  } ],
  "telephone" : "+393332234666"
}
```

**Comment by beppe9000** [comment]
After some fiddling i found that dropping the `@language` part seems to make it work... so for now i first deserialize once, then edit the json and deserialize again. Is there a more practical solution?

**Comment by RehanSaeed** [comment]
Is it valid JSON-LD to have the context like that with a language in it? I'll try adding a unit test and see where I get.

**Comment by beppe9000** [comment]
The specification [describes](https://w3c.github.io/json-ld-syntax/#string-internationalization) languages in a context, but I suspect the json I have to parse may have used an array instead of an object for that... of this I'm not sure if it's valid.

Btw the playground website [does not complain](https://json-ld.org/playground/#startTab=tab-expand&json-ld={%20%20%20"@context"%20:%20[%20"http://schema.org",%20{%20%20%20%20%20"@language"%20:%20"it"%20%20%20}%20],%20%20%20"@type"%20:%20"LocalBusiness",%20%20%20"name"%20:%20"Mario%20Rossi",%20%20%20"url"%20:%20"https://example.com/mario-rossi-srl",%20%20%20"@id"%20:%20"https://example.com/mario-rossi-srl",%20%20%20"legalName"%20:%20"Mario%20Rossi%20s.r.l.",%20%20%20"currenciesAccepted"%20:%20"EUR",%20%20%20"address"%20:%20{%20%20%20%20%20"@type"%20:%20"PostalAddress",%20%20%20%20%20"addressLocality"%20:%20"Venezia",%20%20%20%20%20"addressRegion"%20:%20"VN",%20%20%20%20%20"postalCode"%20:%20"00334",%20%20%20%20%20"streetAddress"%20:%20"10,%20Piazza%20Grande"%20%20%20},%20%20%20"contactPoint"%20:%20[%20{%20%20%20%20%20"@type"%20:%20"ContactPoint",%20%20%20%20%20"contactType"%20:%20"customer%20service",%20%20%20%20%20"telephone"%20:%20"+393332234666"%20%20%20}%20],%20%20%20"telephone"%20:%20"+393332234666"%20})...

**Comment by RehanSaeed** [comment]
Thanks for the links. This exception occurs because `@context` is currently being deserialized to a string.

```c#
public class JsonLdObject
{
    [DataMember(Name = "@context", Order = 0)]
    public virtual string Context { get; }

    [DataMember(Name = "@id", Order = 2)]
    public virtual Uri Id { get; set; }

    [DataMember(Name = "@type", Order = 1)]
    public virtual string Type { get; }
}
```

Here is a unit test that can verify this:

```c#
private const string JsonWithLanguageInContext =
    "{\r\n" +
        "\"@context\": [ \"http://schema.org\", { \"@language\": \"it\" } ],\r\n" +
        "\"@type\": \"LocalBusiness\",\r\n" +
        "\"@id\": \"https://example.com/mario-rossi-srl\",\r\n" +
        "\"name\": \"Mario Rossi\"\r\n" +
    "}";

[Fact]
public void DeserializeObject_WithLanguageInContext_DeserializesSuccessfully()
{
    var localBusiness = JsonConvert.DeserializeObject<LocalBusiness>(JsonWithLanguageInContext);

    // Asserts....
}
```

We could either remove this property because 99% of the time the value is just `schema.org`  or we would need a custom `JsonConverter` to handle this property and any properties it contains like `@language`. I'm not certain how common this scenario is. I'd be willing to take a PR to fix this.
