### ISSUE TITLE
WebPageElement is missing cssSelector

### ISSUE THREAD

**Issue by dewanganlakhan** [RehanSaeed/Schema.NET#638]
### Describe the bug

https://schema.org/WebPageElement

cssSelector and xpath  is missing from WebPageElement

I can see them on the code but when I am using Nuget package with latest release these properties were missing.

### Steps to reproduce

1. install latest package.
2.  create a new variable for WebPageElement.
var webelement = new WebPageElement();
webelement.cssSelector=

### Expected behaviour

I can see the source code is having the property but somehow its missing on nuget release.

 public partial interface IWebPageElement : ICreativeWork
    {
        /// <summary>
        /// A CSS selector, e.g. of a &lt;a class="localLink" href="http://schema.org/SpeakableSpecification"&gt;SpeakableSpecification&lt;/a&gt; or &lt;a class="localLink" href="http://schema.org/WebPageElement"&gt;WebPageElement&lt;/a&gt;. In the latter case, multiple matches within a page can constitute a single conceptual "Web page element".
        /// </summary>
        OneOrMany<string> CssSelector { get; set; }

        /// <summary>
        /// An XPath, e.g. of a &lt;a class="localLink" href="http://schema.org/SpeakableSpecification"&gt;SpeakableSpecification&lt;/a&gt; or &lt;a class="localLink" href="http://schema.org/WebPageElement"&gt;WebPageElement&lt;/a&gt;. In the latter case, multiple matches within a page can constitute a single conceptual "Web page element".
        /// </summary>
        OneOrMany<string> Xpath { get; set; }
    }

### Schema objects

https://schema.org/WebPageElement

**Comment by Turnerj** [comment]
Hey @dewanganlakhan - missed this issue previously, the reason you're not seeing the properties is that the type for them is marked as "new" or "pending" in schema.org.

![image](https://github.com/RehanSaeed/Schema.NET/assets/904226/ed7173c7-80ad-429e-a967-bc49bfe2bf93)

See how the types are blue?

Basically, you'll need to use Schema.NET.Pending instead of Schema.NET to access those types
