### ISSUE TITLE
Schema.org v16 or later

### ISSUE THREAD

**Issue by SmithPlatts** [RehanSaeed/Schema.NET#656]
### Describe the feature

Hi;

Is there a plan to release an update that includes a more recent version of Schema.org? The current Schema.NET v12 uses an older version which is now missing quite a few changes; Schema.org v16 was added to the repo a bit over a week after Schema.NET v12 was published.

Cheers!

**Comment by AlizerUncaged** [comment]
dont bother asking for this, maintainer is lazy

**Comment by Turnerj** [comment]
@AlizerUncaged lazy? No. Busy? Yes.

@SmithPlatts I'll look at doing this along with getting that PR you raised in soon.

**Comment by AlizerUncaged** [comment]
actually nevermind, everything i needed was in the schema.net.pending package, good work for this library
