### ISSUE TITLE
MissingMethodException on constructors

### ISSUE THREAD

**Issue by kirk-marple** [RehanSaeed/Schema.NET#66]
I was noticing a lot of MissingMethodExceptions in my debug console, and noticed I'm getting it on deserializing my objects from an Azure CosmosDB query response.  Looks to be happening a lot, which I'm sure is affecting performance.  (Running with latest VS 2019)

Appears to be happening in here:
Schema.NET.dll!Schema.NET.ValuesJsonConverter.ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)

Exception:
Constructor on type 'Schema.NET.OneOrMany`1[[System.Nullable`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' not found

mscorlib.dll!System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes, ref System.Threading.StackCrawlMark stackMark) Line 5229
	at f:\dd\ndp\clr\src\BCL\system\rttype.cs(5229)

Looks to be happening here:

            object value = converter.ReadJson(reader, objectType, existingValue, GetInternalSerializer());

objectType:

{Name = "Nullable`1" FullName = "System.Nullable`1[[Schema.NET.Values`2[[System.Nullable`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], Schema.NET, Version=4.2.0.0, Culture=neutral, PublicKeyToken=fc5550082a9c642c]]"}

reader.path:
thing.model.position

full JSON (the 'thing' part is a Schema.NET MusicRecording):

> {{
>   "thing": {
>     "model": {
>       "@context": "http://schema.org",
>       "@type": "MusicRecording",
>       "name": "There, There",
>       "identifier": "77SPrxY5gn6VPrKPGrfLnM",
>       "url": "https://open.spotify.com/track/77SPrxY5gn6VPrKPGrfLnM",
>       "isFamilyFriendly": true,
>       "position": "1.9",
>       "byArtist": {
>         "@context": "http://schema.org",
>         "@type": "MusicGroup",
>         "name": "Radiohead",
>         "identifier": "4Z8W4fKeB5YxbusRsdQVPb"
>       },
>       "duration": "PT5M23.6S"
>     }
>   },
>   "ownerType": {
>     "value": 0,
>     "name": "Vendor"
>   },
>   "thingType": {
>     "value": 2,
>     "name": "MusicRecording"
>   },
>   "application": {
>     "id": "73693d68-7b1e-45d2-8294-a5983fe2ae2b"
>   },
>   "sources": {
>     "Spotify": {
>       "feedReaderSession": "45f856e6-34ce-49ed-9a7f-f5db10e131c0",
>       "feedType": {
>         "value": 0,
>         "name": "Vendor"
>       },
>       "feedReaderType": {
>         "value": 1,
>         "name": "HttpProcessor"
>       },
>       "feedReaderIdentifier": "77SPrxY5gn6VPrKPGrfLnM"
>     }
>   },
>   "sourceIdentifiers": [
>     "77SPrxY5gn6VPrKPGrfLnM"
>   ],
>   "feedReaderConnectorType": {
>     "value": 8,
>     "name": "Spotify"
>   },
>   "feedReaderType": {
>     "value": 1,
>     "name": "HttpProcessor"
>   },
>   "feedReaderIdentifier": "77SPrxY5gn6VPrKPGrfLnM",
>   "name": "There, There",
>   "id": "8f534e34-0f76-4302-8fc4-87d23b0da9e8",
>   "state": "Created",
>   "hash": 1857201296850043839,
>   "creationDate": {
>     "date": "2019-06-16T06:50:18Z",
>     "epoch": 1560667818
>   },
>   "type": "Track",
>   "parent": {
>     "id": "03eaa02f-666b-4963-9cb1-f366cfb25507"
>   }
> }}

**Comment by kirk-marple** [comment]
Little more detail here.  I've narrowed it down to, on Thing:

        [JsonConverter(typeof(ValuesJsonConverter))]
        public Values<IPropertyValue, string, Uri>? Identifier { get; set; }

If I remove the 'identifier' line below, I get no exception.

`            const string MUSIC_ALBUM =
            @"{
                ""@context"": ""http://schema.org"",
                ""@type"": ""MusicAlbum"",
                ""name"": ""Hail To the Thief"",
                ""identifier"": ""1oW3v5Har9mvXnGk0x4fHm"",
            }";

            var a = JsonConvert.DeserializeObject<MusicAlbum>(MUSIC_ALBUM);
`

**Comment by kirk-marple** [comment]
Ah, looking at ValuesJsonConverter code, I think I understand.  It's trying each type, and this is normal behavior to get the exception.

                        catch (Exception e)
                        {
                            // Nasty, but we're trying brute force as a last resort, to
                            // see which type has the right constructor for this value
                            Debug.WriteLine(e);
                        }

**Comment by RehanSaeed** [comment]
Ideally, we should find a better way than this.

**Comment by kirk-marple** [comment]
I'd be happy to try and make this a little less messy.  Any prior thoughts you've had on how to attack the problem?

**Comment by kirk-marple** [comment]
@RehanSaeed I cloned the repo and have been looking into this.

It appears ReadJson loops thru each type, attempting to call CreateInstance, and returns the *last* successful one.  Is that intentional?  Is the list of values ordered in a way, where the last one is preferential?

I'm seeing a case where it throws an exception attempting to cast to PropertyValue, but then succeeds on OneOrMany<string> *and* OneOrMany<Uri>, and ends up using the Uri.

It should be easy to special case 'string -> PropertyValue', and avoid that ToObject call, if that's never an expected cast.  What are allowed values to be cast to PropertyValue?

Also, seeing the case where it's trying to assign a date string to OneOrMany<int?> before trying OneOrMany<DateTime?>.

This gives the exception:
{"Constructor on type 'Schema.NET.OneOrMany`1[[System.Nullable`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' not found."}

In this case, unwrappedType is Int32, so it's just assigning "2013-01-01" as args, and trying to pass that to the constructor.

If 'value' is a string, should instead it try to parse the string into the primitive type instead of purely assigning it?  For example, if it used Int32.TryParse, and it failed, it could skip attempting to call Activator.CreateInstance.

                                var unwrappedType = type.GetUnderlyingTypeFromNullable();
                                if (unwrappedType.IsPrimitiveType())
                                {
                                    args = value;
                                }

**Comment by kirk-marple** [comment]
I've refactored ValuesJsonConverter.cs a good bit, and attached it here.  I must be dumb since I can't seem to make a pull request; just seems to hang in SourceTree.

This passes all unit tests, and even better, doesn't hit your exception 'catch' statements for any of the unit tests.  Note some of the // REVIEW comments.

I may have taken liberties with reusing common refactored methods between the single type, and multiple type arg, use cases, but it seems to work.

[ValuesJsonConverter.zip](https://github.com/RehanSaeed/Schema.NET/files/3299831/ValuesJsonConverter.zip)

**Comment by RehanSaeed** [comment]
@kirk-marple Thank you for your contribution. I think you are on the right track. It's been a fairly long time since I really concentrated on this code. I think my original implementation was overriten by a contribution by Pedro and it fixed some issues, so we merged it at the time. However, that try catch has never sat well with me, so I'm glad that you are taking a look at it.
