### ISSUE TITLE
JsonConvert.SerializeObject not writing out enums as string values

### ISSUE THREAD

**Issue by kirk-marple** [RehanSaeed/Schema.NET#68]
I realized there appears to be a bug in using JsonConvert.SerializeObject vs ToString.  In CarTest.cs, if you look at 'this.car', and compare, the outputs are different.

ToString:
			"availability": "http://schema.org/InStock",
SerializeObject:
		"availability": 1,

For objects with enums, which are serialized using SerializeObject, the ValuesJsonConverter.cs will fail upon parsing the enum (expecting a string not an integer).

I've tested that changing each enum class to be in this form solves the issue, and SerializeObject will write out the values upon serialization:

    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// A list of possible product availability options.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ItemAvailability

I've fixed the tool that generates these:
.\Source\Schema.NET.Tool\ViewModels\Enumeration.cs

But will also make ValuesJsonConverter work for deserializing both the string and the integer representation.

Filing a PR shortly.

(Also, I believe this is what #25 was about.)

**Comment by kirk-marple** [comment]
Also, we may want to add in tests to compare ToString and SerializeObject across the board, just in case there are other differences.

**Comment by RehanSaeed** [comment]
Merged your PR. I think writing a few tests will tell us if this is failing.

**Comment by kirk-marple** [comment]
Before I mess anything up, should the semantics of ItemListElement be that the JSON below returns both IThing *and* IListItem, even though it was only serialized as a ListItem?  This seemed like different behavior than the non-list case, where it would only return the first matching type.

The serialization changes I made will only grab the first matching type (from right-to-left), so I'm only returning a list of IListItem.

Also, it felt right to swap positions of IThing and IListItem in Values, so IListItem would take precedence.   Would like your opinion on that.

If this sounds OK, I need to fix a few unit tests which are breaking with this behavior.

        public Values<IThing, string, IListItem>? ItemListElement { get; set; }

`            var json =
            "{" +
                "\"@context\":\"http://schema.org\"," +
                "\"@type\":\"ItemList\"," +
                "\"itemListElement\":[" +
                    "{" +
                        "\"@type\":\"ListItem\"," +
                        "\"item\":{" +
                            "\"@type\":\"Recipe\"," +
                            "\"name\":\"Recipe 1\"" +
                        "}," +
                        "\"position\":1" +
                    "}," +
                    "{" +
                        "\"@type\":\"ListItem\"," +
                        "\"item\":{" +
                            "\"@type\":\"Recipe\"," +
                            "\"name\":\"Recipe 2\"" +
                            "}," +
                        "\"position\":2" +
                    "}" +
                "]" +
            "}";
`

**Comment by kirk-marple** [comment]
Followup, the array handling in ReadJson seems to assume it'll return *any* matching 'generic type argument', but that can end up creating duplicates.  For example <string, Uri?>, you'll get lists of both types, which then end up generating duplicates upon serialization.

I can clean this up, but would like to understand what the expected semantics should be.

**Comment by kirk-marple** [comment]
Question, is this expected semantics for deserializing an array of Uri, when defines as Values<string, Uri?>?

"actionPlatform": ["http://schema.org/DesktopWebPlatform", "http://schema.org/IOSPlatform", "http://schema.org/AndroidPlatform"],

![image](https://user-images.githubusercontent.com/13594550/59888754-13de2a00-937e-11e9-9c9e-33d7cca3a0b5.png)

Similarly, if you have <IThing, string, IListItem>, should it fill in two values (IThing, IListItem) since a list item is also an object?

There are a few issues with arrays and multi-value objects I'm trying to resolve, but need to know if this expected semantics on deserialization.  If reading the JSON into the object is supposed to create multi-values, then we need to do some filtering on the serialization to avoid creating duplicates.

If we serialize this book (from BookTest.cs), it generates an array with 6 entries (3 strings, 3 URI).

**Comment by RehanSaeed** [comment]
It's totally valid to have it as an `IThing` and a `IListItem` at the same time. You can implicity convert the `Values<IThing, string, IListItem>` to `IThing` or `IListItem` and get three items back. Where you are talking about getting six items back, then I think you mean on `Values<T1, T2, T3>.GetEnumerator()` where I think we'd just need to run LINQ's `.Distinct()` on it.

**Comment by kirk-marple** [comment]
It appears that, during serialization, if we have Values<string, Uri>, with 3 items in each collection, we get six items total from values.Cast<object>, which creates the duplicates.

                this.WriteObject(writer, values.Cast<object>().ToList(), serializer);

I'm thinking maybe we flatten each Value<> to only have one value (going right to left), since we'll recreate all the expected values on deserialization.

So, if you had Values<IThing, string, IListItem> and all have values, when we serialize, we just grab only the IListItem.

Make sense?

**Comment by kirk-marple** [comment]
> It's totally valid to have it as an IThing and a IListItem at the same time. You can implicity convert the Values<IThing, string, IListItem> to IThing or IListItem and get three items back. 

I'm wondering if the semantics are correct on Values<> where it will store multiple copies of the object, i.e. as IThing and IListItem?  If you only stored the IListItem, since that can be cast to IThing, it shouldn't break any behavior, I'm thinking?

**Comment by RehanSaeed** [comment]
Yes, perhaps that would be a better approach.
