### ISSUE TITLE
Support Serialize/Deserialize of new Schema.org Objects

### ISSUE THREAD

**Issue by RehanSaeed** [RehanSaeed/Schema.NET#7]
New objects that don't exist in the Schema.NET library should still deserialize to a `Thing` successfully.

1. Write a unit test to confirm that this does or doesn't happen already.
2. Fix it if the unit test confirms that it is not working.
3. Think about how you could write your own custom objects and provide them to the Schema.NET serializer.

**Comment by psampaio** [comment]
I can try to provide this for the deserialization, given that I had input before. But can you clarify what you mean with Serialize new Schema.org objects? We wouldn't have types for those objects, right?

**Comment by RehanSaeed** [comment]
Correct, we won't have a class for any custom objects but we could still deserialize such JSON to a `Thing` object.

**Comment by psampaio** [comment]
Deserialization actually works. I'll submit a PR with the passing test.

**Comment by RehanSaeed** [comment]
Fixed by https://github.com/RehanSaeed/Schema.NET/pull/11 thanks to https://github.com/psampaio
