### ISSUE TITLE
Deserialize fails for Recipe.RecipeInstructions

### ISSUE THREAD

**Issue by brewaa** [RehanSaeed/Schema.NET#75]
**Which [schema.org](https://schema.org) object is this about if any?**

Recipe
https://schema.org/Recipe

Deserializing a recipe fails when changing recipeInstructions from a string to a List<ICreativeWork>.

Snippet from RecipeTest.cs:

```
var recipe = new Recipe()
        {
            Name = "Grandma's Holiday Apple Pie",
            // RecipeInstructions = "1. Cut and peel apples...",
            RecipeInstructions = new List<ICreativeWork>()
            {
                new HowToStep { Text = "Do something" },
                new HowToStep { Text = "Do something else" }
            }
        };
```
Corresponding json snippet in RecipeTest.cs:
```
"\"recipeInstructions\":[" +
                "{\"@type\":\"HowToStep\",\"text\":\"Do something\"}," +
                "{\"@type\":\"HowToStep\",\"text\":\"Do something else\"}" +
            "]," +
```
Is deserialization working for all types? 

public Values<ICreativeWork, IItemList, string>? RecipeInstructions { get; set; }

**Comment by kirk-marple** [comment]
I've been working on the JSON serialization recently.  I just updated my changes to support this use case, and updated RecipeTest.cs to use HowToSteps not strings.

@RehanSaeed I'll update my recent PR with these changes.

**Comment by brewaa** [comment]
Nice work @kirk-marple. Looking forward to getting my hands on these changes.

Should the test for Recipe include an example that uses either of the three available types for Values<ICreativeWork, IItemList, string>RecipeInstructions?

If you know that string, IListItem and ICreativeWork is being used successfully in another test, I guess that should be fine.

**Comment by RehanSaeed** [comment]
Just merged @kirk-marple's PR. I'll see if I can get a release out now. Closing this issue for now. Feel free to reopen if the next release doesn't fix this issue.

**Comment by brewaa** [comment]
It's working for me now guys. Appreciate your efforts!

**Comment by RehanSaeed** [comment]
Wonderful, thanks to @kirk-marple for most of the work and @brewaa for raising the issue.
